### ISSUE TITLE
Addiction-related statuses are crashing the game

### ISSUE THREAD

**Issue by GynoidDoesGames** [Ryplinn/nightgamesmod#20]
For some reason, Jewel's Induced Submission status (apparently the Addiction Symptom for a Dominance Addiction) seems to be crashing the game repeatedly with NullPointerExceptions strewn throughout the code. Examples include:

```
java.lang.NullPointerException
	at nightgames.characters.body.Body.lambda$10(Body.java:611)
	at java.util.stream.ReferencePipeline$6$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.DoublePipeline.collect(Unknown Source)
	at java.util.stream.DoublePipeline.sum(Unknown Source)
	at nightgames.characters.body.Body.pleasure(Body.java:612)
```

```
java.lang.NullPointerException
	at nightgames.characters.Character.lambda$85(Character.java:3904)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
```

I'm working on tracking down what's causing this, but I'm not having luck so far. This didn't cause problems in the January 2019 build, so it seems to be related in part to the changes that introduced AddictionSymptom.

EDIT: This might actually be all withdrawalEffect types, because Kat just crashed my game too.

**Comment by GynoidDoesGames** [comment]
The scenario most frequently causing the game to crash is exiting combat, leating me to believe that refreshWithdrawal() is one of the primary culprits; but in general, it seems like the game really doesn't like treating withdrawalEffects() entries as real statuses.

**Comment by Ryplinn** [comment]
Do you have a save file that can easily reproduce this?

**Comment by GynoidDoesGames** [comment]
This is the exact save I'm using, minus the fact that I changed the player character's name.

This does not happen every night -- I would have saved right before it was about to happen if I could save in the middle of a night - but go and find Kat or Jewel and then exit a fight with them after getting an addiction status, and that should do it.
[save.zip](https://github.com/Ryplinn/nightgamesmod/files/4802293/save.zip)

**Comment by Ryplinn** [comment]
I found similar problems with my own saves, and I think I have a fix, although I haven't tried your save yet. The primary issue is that AddictionSymptom.instance() would return null if it couldn't find the right addiction; the secondary issue is that AddictionSymptom.instance() should always be able to find the right addiction, since why would you have addiction symptoms with no addiction?

Will push soon.

**Comment by Ryplinn** [comment]
I think this problem is fixed, but please re-open the issue if it's not.

**Comment by GynoidDoesGames** [comment]
Crash still happens, it's just giving a more useful message now:
```
An error we didn't expect occurred:
java.lang.RuntimeException: Could not create symptom instance for addiction nightgames.status.addiction.MindControl@930e6c3f. Afflicted: Player, Source: Mara
	at nightgames.status.addiction.AddictionSymptom.lambda$instance$0(AddictionSymptom.java:45)
```

**Comment by Ryplinn** [comment]
I tried playing your save for a while, but didn't manage to trigger that error. I just pushed some changes; does it still happen with those?
